In [4]:
import numpy as np
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
%config InlineBackend.figure_formats = ['svg']




In [33]:
import numpy as np
import abc
# Basic class of Network description
class Network(object, metaclass=abc.ABCMeta):
    """
    Basic network class.
    This class is used to create the frame of network by setting weigts
    """
    def __init__(self, size=1, weigths=[]):
        self._size_ = size;
        self._weigths_ = weigths;


    @property
    def weigths(self):
        '''Getting weights of the network(Property).'''
        return self._weigths_

    @abc.abstractmethod
    def _model_(self):
        '''Neuron dynamics mathematical model(method).'''
        pass
        
class Synapses(object, metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def __init__(self):
        pass
    @abc.abstractmethod
    def model(self):
        '''Synapses dynamics maths model(method).'''
        pass
    
class Izhikevich_Network(Network):
    def __init__(self, **kwargs):
        Network.__init__(size=kwargs['size'], weigths=kwargs['weigths']);

    def _model_(self, V, U, I, Isyn):
        dV = 0.04*np.power(V, 2) + 5*V + 140 - U + I + Isyn;
        dU = a(b*V-u)
        
help(Synapses)
help(Network)
help(Izhikevich_Network)

Help on class Synapses in module __main__:

class Synapses(builtins.object)
 |  Methods defined here:
 |  
 |  __init__(self)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  model(self)
 |      Synapses dynamics maths model(method).
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)
 |  
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |  
 |  __abstractmethods__ = frozenset({'__init__', 'model'})

Help on class Network in module __main__:

class Network(builtins.object)
 |  Network(size=1, weigths=[])
 |  
 |  Basic network class.
 |  This class is used to create the frame of network by setting weigts
 |  
 |  Methods defined here:
 |  
 |  __init__(self, size=1, weigths

In [12]:
import numpy as np
a = np.array([1, 2, 3, 4])
A = np.eye(4)
diag_view = np.einsum('ii->i', A)[:] = a
diag_view
A

array([[1., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 3., 0.],
       [0., 0., 0., 4.]])

In [14]:
np.zeros((10, 2, 2))[0]

array([[0., 0.],
       [0., 0.]])

In [19]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[3, 4], [5, 6]])
b.sum(axis=1
     )

array([ 7, 11])

In [21]:
W=np.array([
    [1, 2],
    [3, 4]
])
v = np.array([1, 4])
W*v

array([[ 1,  8],
       [ 3, 16]])